### ISSUE TITLE
Not compatible with  Liveview 0.17.11

### ISSUE THREAD

**Issue by antoinereyt** [akira/exq_ui#120]
After an update of all the deps of my Phoenix app, I got this error:

> ** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/exq_ui_web/live/components/table_component.html.heex:1:1: attribute "phx-hook" requires the "id" attribute to be set

Full error:
```
==> exq_ui
Compiling 26 files (.ex)
== Compilation error in file lib/exq_ui_web/live/components/table_component.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/exq_ui_web/live/components/table_component.html.heex:1:1: attribute "phx-hook" requires the "id" attribute to be set
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/html_engine.ex:795: Phoenix.LiveView.HTMLEngine.validate_phx_attrs!/5
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/html_engine.ex:435: Phoenix.LiveView.HTMLEngine.handle_token/2
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/html_engine.ex:53: Phoenix.LiveView.HTMLEngine.handle_body/1
    (phoenix_live_view 0.17.11) expanding macro: Phoenix.LiveView.Renderer.__before_compile__/1
    lib/exq_ui_web/live/components/table_component.ex:1: ExqUIWeb.TableComponent (module)
could not compile dependency :exq_ui, "mix compile" failed. You can recompile this dependency with "mix deps.compile exq_ui", update it with "mix deps.update exq_ui" or clean it with "mix deps.clean exq_ui"
```

I'm making a PR.

**Comment by antoinereyt** [comment]
My bad I wasn't on the last release, sorry for the noise.
