### ISSUE TITLE
error when clicking in "schedule" button

### ISSUE THREAD

**Issue by henry-hz** [akira/exq_ui#25]
Interactive Elixir (1.3.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>  time = Timex.Date.from({{2017, 9, 5}, {15, 54, 0}}) |> Timex.Date.to_timestamp
{1504, 569600, 0}
iex(2)> {:ok, ack} = Exq.enqueue_at(Exq, "bots", time, Sentinel.Execution, ["arg1", "arg2"])
{:ok, "c2e61709-04b5-4983-bea1-7c64a5cd2589"}
iex(3)>
15:57:48.763 [error] Ranch listener ExqUi.RouterPlug.HTTP had connection process started with :cowboy_protocol:start_link/4 at #PID<0.395.0> exit with reason: {{%ArgumentError{message: "argument error"}, [{:erlang, :binary_to_float, ["1504569600"], []}, {ExqUi.RouterPlug.Router, :score_to_time, 1, [file: 'web/router.ex', line: 199]}, {ExqUi.RouterPlug.Router, :"-map_score_to_jobs/1-fun-0-", 1, [file: 'web/router.ex', line: 209]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line:
1092]}, {ExqUi.RouterPlug.Router, :"-do_match/4-fun-5-", 1, [file: 'web/router.ex', line: 80]}, {ExqUi.RouterPlug.Router, :plug_builder_call, 2, [file: 'web/router.ex', line: 34]}, {Plug.Adapters.Cowboy.Handler, :upgrade, 4, [file: 'lib/plug/adapters/cowboy/handler.ex', line: 15]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 442]}]}, {ExqUi.RouterPlug, :call, [%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params:
%Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "GET", owner: #PID<0.395.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["api", "scheduled"], peer: {{127, 0, 0, 1}, 48621}, port: 4040, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "localhost:4040"},
{"connection", "keep-alive"}, {"accept", "application/json, text/javascript, _/_; q=0.01"}, {"x-requested-with", "XMLHttpRequest"}, {"user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"}, {"referer", "http://localhost:4040/"}, {"accept-encoding", "gzip, deflate, sdch"}, {"accept-language", "en-US,en;q=0.8,pt;q=0.6,he;q=0.4"}, {"cookie", "_ga=GA1.1.975442743.1458598151"}], request_path: "/api/scheduled", resp_body: nil,
resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, [exq_opts: [name: Exq.Api], namespace: ""]]}}

**Comment by pdilyard** [comment]
I also get an error when trying to view the "scheduled" page, here's my traceback:

```
[error] #PID<0.747.0> running ExqUi.RouterPlug terminated
Server: localhost:4040 (http)
Request: GET /api/scheduled
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.binary_to_float("1471541400")
        (exq_ui) web/router.ex:199: ExqUi.RouterPlug.Router.score_to_time/1
        (exq_ui) web/router.ex:209: anonymous fn/1 in ExqUi.RouterPlug.Router.map_score_to_jobs/1
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (exq_ui) web/router.ex:80: anonymous fn/1 in ExqUi.RouterPlug.Router.do_match/4
        (exq_ui) web/router.ex:34: ExqUi.RouterPlug.Router.plug_builder_call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by chelsea** [comment]
I was having the same issue but updating to exq 0.8.1 and exq_ui 0.8.2 seems to have sorted it out for me, might be worth trying.

**Comment by mbuhot** [comment]
Also seeing this error on exq 0.8.1 and exq_ui 0.8.2 when clicking the `failed` link:

`http://myapp/exq/api/failures`

```
Elixir.ArgumentError: argument error
  Module "erlang", in :erlang.binary_to_float("2016-06-28T05:38:40.130+00:00")
  File "web/router.ex", line 220, in ExqUi.RouterPlug.Router.score_to_time/1
  File "web/router.ex", line 208, in anonymous fn/3 in ExqUi.RouterPlug.Router.convert_results_to_times/2
  File "lib/enum.ex", line 1623, in Enum."-reduce/3-lists^foldl/2-0-"/3
  File "web/router.ex", line 207, in ExqUi.RouterPlug.Router.convert_results_to_times/2
  File "web/router.ex", line 94, in anonymous fn/1 in ExqUi.RouterPlug.Router.do_match/4
  File "web/router.ex", line 34, in ExqUi.RouterPlug.Router.plug_builder_call/2
  File "lib/panoramix/api/exq/router.ex", line 6, in Panoramix.Api.Exq.Router.exq/2
```

**Comment by akira** [comment]
@mbuhot I'm not able to replicate this, can you post what's in your Redis queue for "exq:schedule" (value and score)? 

You can use something like https://redisdesktop.com/ for easier inspection.

**Comment by theRealWardo** [comment]
@akira I am able to reproduce this running exq 0.8.3 and exq_ui 0.8.4

```
localhost:6379> zrange exq:schedule 0 10 WITHSCORES
1) "{\"queue\":\"default\",\"jid\":\"dc32cad5-da5c-4270-8364-f1f180b2528e\",\"enqueued_at\":1489611448.504912,\"class\":\"SubscriptionWorker\",\"args\":[\"subscription.invoice\",\"REDACTED\"],\"retry\":25}"
2) "1489618648"
```

taking a look now to see what I can do to help fix this problem.

**Comment by theRealWardo** [comment]
PR open. basically, the code assumed the score was always a float. if the score is a string, it will now check to see the score looks like a float and if it does then it will handle as it did in the past. otherwise, it handles the integer case as a second based timestamp. that fixes at least my and @pdilyard's case. I didn't get it patched up to fix @mbuhot's case where it seems there's a full ISO 8601 string as the score.

**Comment by akira** [comment]
Still issue with date format.

**Comment by mbuhot** [comment]
We ended up clearing our failed jobs lists to resolve the issue.
