### ISSUE TITLE
Warming on Erlang release 21

### ISSUE THREAD

**Issue by AllanKlaus** [akira/exq_ui#71]
I'm using the docker image `elixir:1.8`  and i'm getting the following warming.

```
warning: Plug.Adapters.Cowboy2 is deprecated, please use Plug.Cowboy instead
(plug) lib/plug/adapters/cowboy2.ex:12: Plug.Adapters.Cowboy2.http/3
(exq_ui) lib/exq_ui.ex:24: ExqUi.launch_app/0
(kernel) application_master.erl:277: :application_master.start_it_old/4
```

**Comment by omar8792** [comment]
hi @akira and thanks for the fix.
Can you please release a new version?
