### ISSUE TITLE
Server false doesn't seem to prevent the app from starting

### ISSUE THREAD

**Issue by marcelolebre** [akira/exq_ui#78]
When trying to start exq_ui with the following configs:

```  
  config :exq,
    start_on_application: false

  config :exq_ui,
    web_port: 4040,
    web_namespace: "",
    server: false
```

The app crashes when starting:

```
21:40:02.619 [error] Failed to connect to Redis (127.0.0.1:6379): connection refused
21:40:02.632 [error] GenServer ExqUi.Api terminating
** (MatchError) no match of right hand side value: {:error, %Redix.ConnectionError{reason: :closed}}
    (exq) lib/exq/redis/connection.ex:63: Exq.Redis.Connection.smembers!/2
    (exq) lib/exq/redis/job_queue.ex:296: Exq.Redis.JobQueue.queue_size/2
    (exq) lib/exq/api/server.ex:84: Exq.Api.Server.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.1811.0>): :queue_size
State: %Exq.Api.Server.State{namespace: "exq", redis: ExqUi.Redis.Client}
Client #PID<0.1811.0> is alive

    (stdlib) gen.erl:167: :gen.do_call/4
    (elixir) lib/gen_server.ex:1006: GenServer.call/3
    (exq_ui) lib/exq_ui.ex:20: ExqUi.launch_app/0
    (kernel) application_master.erl:277: :application_master.start_it_old/4
```

**Comment by marcelolebre** [comment]
I believe this is related to: https://github.com/akira/exq_ui/issues/56

I'd be happy to pick it up and solve it myself.

**Comment by akira** [comment]
@marcelolebre sounds good that would be great if you have time.  Thanks!

**Comment by ananthakumaran** [comment]
This shouldn't be an issue in the latest version, since exq_ui doesn't start the supervisor anymore.
